Vectorization Example  

In [9]:
import numpy as np
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

#Vectorization Example
tic =time.time()
c=np.dot(a,b)
print(c)
toc =time.time()
print("Total time in the Vectorization :" + str(1000*(toc-tic)) +"ms")

#Non Vector Exmaple 
tic =time.time()
c=0
for i in range(1000000):
    c+= a[i]*b[i]
print(c)
toc =time.time()
print("Total time in the non vectorization(For loop) :" + str(1000*(toc-tic)) +"ms")





249780.60631962836
Total time in the Vectorization :0.9989738464355469ms
249780.60631963404
Total time in the non vectorization(For loop) :469.2730903625488ms


Broadcasting in python  

In [23]:
import numpy as np

A =np.array([[56.0,0.0,4.4,68.9],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])
print(A)

cal = A.sum(axis=0)
print("\n"+str(cal)+"\n")

per =100*A/cal.reshape(1,4)
print(per)

[[ 56.    0.    4.4  68.9]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]

[ 59.  239.  155.4  77.8]

[[94.91525424  0.          2.83140283 88.56041131]
 [ 2.03389831 43.51464435 33.46203346 10.28277635]
 [ 3.05084746 56.48535565 63.70656371  1.15681234]]
