### Vectorization Example  

In [9]:
import numpy as np
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

#Vectorization Example
tic =time.time()
c=np.dot(a,b)
print(c)
toc =time.time()
print("Total time in the Vectorization :" + str(1000*(toc-tic)) +"ms")

#Non Vector Exmaple 
tic =time.time()
c=0
for i in range(1000000):
    c+= a[i]*b[i]
print(c)
toc =time.time()
print("Total time in the non vectorization(For loop) :" + str(1000*(toc-tic)) +"ms")





249780.60631962836
Total time in the Vectorization :0.9989738464355469ms
249780.60631963404
Total time in the non vectorization(For loop) :469.2730903625488ms


### Broadcasting in python  

In [23]:
import numpy as np

A =np.array([[56.0,0.0,4.4,68.9],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])
print(A)

cal = A.sum(axis=0)
print("\n"+str(cal)+"\n")

per =100*A/cal.reshape(1,4)
print(per)

[[ 56.    0.    4.4  68.9]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]

[ 59.  239.  155.4  77.8]

[[94.91525424  0.          2.83140283 88.56041131]
 [ 2.03389831 43.51464435 33.46203346 10.28277635]
 [ 3.05084746 56.48535565 63.70656371  1.15681234]]


### A note on python or numpy vectors
 

In [65]:
import numpy as np

a = np.random.rand(5)

print(a)

[0.13422812 0.03647177 0.39278917 0.03448107 0.30419289]


In [66]:
#rank 1 vector dont use 
print(a.shape)

(5,)


In [67]:
print(a.T)

[0.13422812 0.03647177 0.39278917 0.03448107 0.30419289]


In [68]:
print(np.dot(a,a.T))

0.26735297028207555


In [69]:
a =np.random.rand(5,1) #Column vector
print(a)

[[0.06943091]
 [0.58522524]
 [0.95728367]
 [0.41192933]
 [0.924286  ]]


In [70]:
print(a.T)

[[0.06943091 0.58522524 0.95728367 0.41192933 0.924286  ]]


In [71]:
print(np.dot(a,a.T))

[[0.00482065 0.04063272 0.06646508 0.02860063 0.06417402]
 [0.04063272 0.34248859 0.56022657 0.24107144 0.5409155 ]
 [0.06646508 0.56022657 0.91639202 0.39433322 0.88480389]
 [0.02860063 0.24107144 0.39433322 0.16968577 0.38074051]
 [0.06417402 0.5409155  0.88480389 0.38074051 0.85430461]]


In [72]:
a =np.random.rand(1,5) #Row vector
print(a)

[[5.32902960e-04 2.62127652e-01 7.20458957e-01 9.13340621e-01
  9.86732297e-01]]
